import React, { useEffect, useState } from 'react';
import api from '../../lib/api';
import FeatureWall from '../upgrade/FeatureWall';

/**
 * ViewerStoriesSection
 *
 * Renders 4 narrative story cards per video generated by the story engine.
 * Each story type has a different plan requirement:
 *
 *   most_engaged        → Pro  (viewer_level)
 *   common_drop_pattern → Pro  (heatmap)
 *   source_pattern      → Pro  (audience_segmentation)
 *   mobile_pattern      → Starter+ (device_breakdown)
 *
 * Plan behaviour:
 *   free           → FeatureWall over fake preview cards (no API call)
 *   starter        → real stories fetched; Pro story types shown as locked cards
 *   pro/admin_life → all real stories shown
 */

// ─────────────────────────────────────────────────────────────────────────
// Story type metadata
// ─────────────────────────────────────────────────────────────────────────

const STORY_META = {
  most_engaged: {
    label       : 'Most Engaged Viewer',
    icon        : '⭐',
    feature     : 'viewer_level',
    requiredPlan: 'pro',
    accentClass : 'border-l-amber-400',
    fakeHeadline: 'One viewer gave this video their complete attention',
    fakeDetail  : 'A viewer arriving via email watched 94% of the video on desktop. They rewound twice and watched without muting — no persuasion needed.',
  },
  common_drop_pattern: {
    label       : 'Viewing Pattern',
    icon        : '〜',
    feature     : 'heatmap',
    requiredPlan: 'pro',
    accentClass : 'border-l-red-400',
    fakeHeadline: 'Most viewers stop around the halfway point',
    fakeDetail  : '54% of your sessions result in viewers stopping between the 25–50% mark. Only 18% of viewers make it to the end.',
  },
  source_pattern: {
    label       : 'Traffic Sources',
    icon        : '◈',
    feature     : 'audience_segmentation',
    requiredPlan: 'pro',
    accentClass : 'border-l-indigo-400',
    fakeHeadline: 'Viewers from email watch significantly more than those from social',
    fakeDetail  : 'Email referrals average 68% watch time vs 29% from social media — a 39-point gap across tracked sources.',
  },
  mobile_pattern: {
    label       : 'Mobile vs Desktop',
    icon        : '▣',
    feature     : 'device_breakdown',
    requiredPlan: 'starter',
    accentClass : 'border-l-emerald-400',
    fakeHeadline: '61% of your audience watches on mobile — and here is how they behave',
    fakeDetail  : 'Mobile viewers watch an average of 44% of the video, compared to 62% on desktop. 38% of mobile sessions include sound.',
  },
};

const STORY_ORDER = ['most_engaged', 'common_drop_pattern', 'source_pattern', 'mobile_pattern'];
const PRO_PLANS   = new Set(['pro', 'admin_lifetime']);

// ─────────────────────────────────────────────────────────────────────────
// ViewerStoriesSection — main export
// ─────────────────────────────────────────────────────────────────────────

export default function ViewerStoriesSection({ videoId, userPlan }) {
  const isFree   = userPlan === 'free';
  const isPro    = PRO_PLANS.has(userPlan);

  const [status,   setStatus]   = useState('idle');
  const [data,     setData]     = useState(null);
  const [retryKey, setRetryKey] = useState(0);

  useEffect(() => {
    if (isFree || !videoId) return;

    let cancelled = false;
    setStatus('loading');

    api.get(`/videos/${videoId}/stories`)
      .then(res => {
        if (cancelled) return;
        setData(res.data);
        setStatus('loaded');
      })
      .catch(() => {
        if (!cancelled) setStatus('error');
      });

    return () => { cancelled = true; };
  }, [videoId, isFree, retryKey]);

  return (
    <div>
      {/* Section header */}
      <div className="flex items-center gap-2 mb-4">
        <span className="text-gray-500 text-sm" aria-hidden="true">◎</span>
        <h2 className="text-base font-semibold text-gray-200">Viewer Stories</h2>
      </div>

      {isFree ? (
        /* Free — blurred fake preview behind upgrade wall */
        <FeatureWall
          feature="viewer_level"
          requiredPlan="pro"
          currentPlan={userPlan}
          minHeight="220px"
        >
          <FakeStoriesPreview />
        </FeatureWall>
      ) : (
        <StoriesContent
          status={status}
          data={data}
          userPlan={userPlan}
          isPro={isPro}
          onRetry={() => setRetryKey(k => k + 1)}
        />
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// StoriesContent — state dispatcher for Starter / Pro users
// ─────────────────────────────────────────────────────────────────────────

function StoriesContent({ status, data, userPlan, isPro, onRetry }) {
  if (status === 'idle' || status === 'loading') {
    return <StoriesSkeleton />;
  }

  if (status === 'error') {
    return (
      <div className="bg-gray-800/30 border border-gray-700/40 rounded-xl px-5 py-6 text-center">
        <p className="text-sm text-gray-400 mb-3">Could not load viewer stories.</p>
        <button
          onClick={onRetry}
          className="text-xs text-amber-400 hover:text-amber-300 transition-colors
                     px-3 py-1.5 border border-amber-500/30 rounded-lg"
        >
          Try again
        </button>
      </div>
    );
  }

  const { stories = [], story_status } = data ?? {};

  // Build a map of existing stories by type for quick lookup
  const storyMap = Object.fromEntries(stories.map(s => [s.story_type, s]));

  // Determine which story types to show based on plan
  const storyTypesToShow = isPro
    ? STORY_ORDER
    : STORY_ORDER.filter(t => STORY_META[t].requiredPlan !== 'pro'); // Starter sees mobile_pattern

  // For Pro stories, locked slots are shown for Starter users
  const lockedProTypes = isPro ? [] : STORY_ORDER.filter(t => STORY_META[t].requiredPlan === 'pro');

  // Generating state — use different UI depending on whether engine is actively
  // running (generating) vs waiting for more data (pending)
  if (story_status === 'pending' || story_status === 'generating') {
    const isGenerating = story_status === 'generating';
    return (
      <div className="bg-gray-800/30 border border-gray-700/40 border-dashed rounded-xl px-5 py-8 text-center">
        {isGenerating
          ? <div className="w-5 h-5 border-2 border-amber-500 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          : <div className="text-2xl mb-3">◎</div>
        }
        <p className="text-sm text-gray-300">
          {isGenerating ? 'Generating viewer stories…' : 'Waiting for more viewers'}
        </p>
        <p className="text-xs text-gray-400 mt-1">Stories appear once 5 or more viewers have watched.</p>
      </div>
    );
  }

  // No stories at all — waiting for data
  const hasAnyStories = stories.length > 0;
  if (!hasAnyStories && lockedProTypes.length === 0) {
    return (
      <div className="bg-gray-800/30 border border-gray-700/40 border-dashed rounded-xl px-5 py-8 text-center">
        <p className="text-sm text-gray-400">No viewer stories yet.</p>
        <p className="text-xs text-gray-400 mt-1">Stories appear once 5 or more viewers have watched.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      {/* Real stories */}
      {storyTypesToShow.map(type => {
        const story = storyMap[type];
        if (!story) return null;
        return <StoryCard key={type} story={story} meta={STORY_META[type]} />;
      })}

      {/* Locked Pro story cards for Starter users */}
      {lockedProTypes.map(type => (
        <LockedStoryCard key={type} meta={STORY_META[type]} userPlan={userPlan} />
      ))}

      {/* Upgrade nudge for Starter */}
      {!isPro && lockedProTypes.length > 0 && (
        <p className="text-xs text-gray-400 text-center mt-1">
          {lockedProTypes.length} more story type{lockedProTypes.length !== 1 ? 's' : ''} unlock on Pro.
        </p>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// StoryCard — a real story from the DB
// ─────────────────────────────────────────────────────────────────────────

function StoryCard({ story, meta }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div
      className={`bg-gray-800/50 border border-gray-700/50 border-l-2
                  ${meta.accentClass} rounded-xl overflow-hidden`}
    >
      {/* Header */}
      <div className="px-5 pt-4 pb-3">
        <div className="flex items-center justify-between gap-3 mb-2">
          <div className="flex items-center gap-2">
            <span className="text-xs text-gray-400" aria-hidden="true">{meta.icon}</span>
            <span className="text-xs text-gray-400 font-medium uppercase tracking-wider">
              {meta.label}
            </span>
          </div>
          {story.viewer_count > 0 && (
            <span className="text-xs text-gray-400 flex-shrink-0">
              {story.viewer_count.toLocaleString()} viewer{story.viewer_count !== 1 ? 's' : ''}
            </span>
          )}
        </div>

        <p className="text-sm font-semibold text-gray-100 leading-snug">
          {story.headline}
        </p>
        <p className="text-sm text-gray-400 mt-2 leading-relaxed">
          {story.detail}
        </p>
      </div>

      {/* Expandable interpretation */}
      <div className="border-t border-gray-700/50">
        <button
          onClick={() => setExpanded(e => !e)}
          className="w-full flex items-center justify-between px-5 py-2.5
                     text-xs text-gray-400 hover:text-gray-200 transition-colors text-left"
        >
          <span>What this means for your video</span>
          <ChevronIcon expanded={expanded} />
        </button>

        {expanded && (
          <div className="px-5 pb-4">
            <div className="bg-gray-800/60 border border-gray-700/40 rounded-lg px-4 py-3">
              <p className="text-sm text-gray-300 leading-relaxed">
                {story.interpretation}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// LockedStoryCard — blurred preview for Pro stories when user is Starter
// ─────────────────────────────────────────────────────────────────────────

function LockedStoryCard({ meta, userPlan }) {
  return (
    <FeatureWall
      feature={meta.feature}
      requiredPlan={meta.requiredPlan}
      currentPlan={userPlan}
      minHeight="100px"
    >
      {/* Fake card that gets blurred */}
      <div
        className={`bg-gray-800/50 border border-gray-700/50 border-l-2
                    ${meta.accentClass} rounded-xl px-5 py-4`}
      >
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs text-gray-500">{meta.icon}</span>
          <span className="text-xs text-gray-500 font-medium uppercase tracking-wider">
            {meta.label}
          </span>
        </div>
        <p className="text-sm font-semibold text-gray-100 leading-snug mb-2">
          {meta.fakeHeadline}
        </p>
        <p className="text-sm text-gray-400 leading-relaxed line-clamp-2">
          {meta.fakeDetail}
        </p>
      </div>
    </FeatureWall>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// FakeStoriesPreview — 3 blurred cards shown inside FeatureWall for free users
// ─────────────────────────────────────────────────────────────────────────

function FakeStoriesPreview() {
  return (
    <div className="flex flex-col gap-3">
      {['most_engaged', 'common_drop_pattern', 'mobile_pattern'].map(type => {
        const meta = STORY_META[type];
        return (
          <div
            key={type}
            className={`bg-gray-800/50 border border-gray-700/50 border-l-2
                        ${meta.accentClass} rounded-xl px-5 py-4`}
          >
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xs text-gray-500">{meta.icon}</span>
              <span className="text-xs text-gray-500 font-medium uppercase tracking-wider">
                {meta.label}
              </span>
            </div>
            <p className="text-sm font-semibold text-gray-100 leading-snug mb-1">
              {meta.fakeHeadline}
            </p>
            <p className="text-xs text-gray-500 line-clamp-2">
              {meta.fakeDetail}
            </p>
          </div>
        );
      })}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// StoriesSkeleton
// ─────────────────────────────────────────────────────────────────────────

function StoriesSkeleton() {
  return (
    <div className="flex flex-col gap-4 animate-pulse">
      {[1, 2].map(i => (
        <div key={i} className="bg-gray-800/50 border border-gray-700/40 rounded-xl px-5 py-4">
          <div className="h-3 w-32 bg-gray-700/60 rounded mb-3" />
          <div className="h-4 w-3/4 bg-gray-700/50 rounded mb-2" />
          <div className="h-3 w-full bg-gray-700/40 rounded mb-1" />
          <div className="h-3 w-2/3 bg-gray-700/40 rounded" />
        </div>
      ))}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// Shared: ChevronIcon
// ─────────────────────────────────────────────────────────────────────────

function ChevronIcon({ expanded }) {
  return (
    <svg
      width="12" height="12" viewBox="0 0 24 24" fill="none"
      stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"
      className={`flex-shrink-0 transition-transform duration-200 ${expanded ? 'rotate-180' : ''}`}
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}
